###############################################################################
# Copyright (c) 2020, 2020 IBM Corp. and others
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which accompanies this
# distribution and is available at https://www.eclipse.org/legal/epl-2.0/
# or the Apache License, Version 2.0 which accompanies this distribution and
# is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# This Source Code may also be made available under the following
# Secondary Licenses when the conditions for such availability set
# forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
# General Public License, version 2 with the GNU Classpath
# Exception [1] and GNU General Public License, version 2 with the
# OpenJDK Assembly Exception [2].
#
# [1] https://www.gnu.org/software/classpath/license.html
# [2] http://openjdk.java.net/legal/assembly-exception.html
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
###############################################################################

name: "PR build-jdk-openj9 jdk 14"
on:
  schedule:
    - cron:  '30 21 * * 1-5'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, macos-10.15]
    steps:
    - uses: sophia-guo/build-jdk-openj9@v1
      id: buildJDK
      with: 
        version: 14
    - name: AQA
      uses: AdoptOpenJDK/run-aqa@v1
      env:
        TEST_JDK_HOME: ${{ steps.buildJDK.outputs.BuildJDKDir }}
      with:
        build_list: 'functional'
        target: '_sanity'
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test_output
        path: ./**/test_output_*/
